/**
 * \file	regs_18F4550.h
 * \brief	Definições dos registros e bits dos registros
 * \warning É necessário comentar / descomentar mantendo uma relação 1 para 1
 * \todo 	Acrescentar registros do PIC conforme a necessidade
 * \date \ref s7
 */

#BYTE PORTA = 0x0F80
	//#BIT RA0 = PORTA.0
	#BIT PAN0 = PORTA.0

	//#BIT RA1 = PORTA.1
	#BIT PAN1 = PORTA.1

	//#BIT RA2 = PORTA.2
	#BIT PAN2 = PORTA.2
	//#BIT VREFN = PORTA.2
	//#BIT CVREF = PORTA.2

	#BIT PAN3 = PORTA.3
	//#BIT RA3 = PORTA.3
	//#BIT VREFP = PORTA.3

	#BIT RA4 = PORTA.4
	//#BIT T0CKI = PORTA.4
	//#BIT C1OUT_PORTA = PORTA.4

	#BIT RA5 = PORTA.5
	//#BIT AN4 = PORTA.5
	//#BIT SS = PORTA.5
	//#BIT NOT_SS = PORTA.5
	//#BIT LVDIN = PORTA.5
	//#BIT HLVDIN = PORTA.5
	//#BIT C2OUT_PORTA = PORTA.5

	#BIT RA6 = PORTA.6
	//#BIT OSC2 = PORTA.6
	//#BIT CLKO = PORTA.6

	#BIT RA7 = PORTA.7
	//#BIT OSC1 = PORTA.7
	//#BIT CLKI = PORTA.7

#BYTE PORTB = 0x0F81
	#BIT RB0 = PORTB.0
	//#BIT INT0 = PORTB.0
	//#BIT AN12 = PORTB.0
	//#BIT FLT0 = PORTB.0

	#BIT RB1 = PORTB.1
	//#BIT INT1 = PORTB.1
	//#BIT AN10 = PORTB.1

	#BIT RB2 = PORTB.2
	//#BIT INT2 = PORTB.2
	//#BIT AN8 = PORTB.2

	#BIT RB3 = PORTB.3
	//#BIT CCP2_PORTB = PORTB.3
	//#BIT AN9 = PORTB.3

	#BIT RB4 = PORTB.4
	//#BIT KBI0 = PORTB.4
	//#BIT AN11 = PORTB.4

	#BIT RB5 = PORTB.5
	//#BIT KBI1 = PORTB.5
	//#BIT PGM = PORTB.5

	#BIT RB6 = PORTB.6
	//#BIT KBI2 = PORTB.6
	//#BIT PGC = PORTB.6

	#BIT RB7 = PORTB.7
	//#BIT KBI3 = PORTB.7
	//#BIT PGD = PORTB.7

#BYTE PORTC = 0x0F82
	#BIT RC0 = PORTC.0
	//#BIT T1OSO = PORTC.0
	//#BIT T13CKI = PORTC.0

	#BIT RC1 = PORTC.1
	//#BIT T1OSI = PORTC.1
	//#BIT CCP2_PORTC = PORTC.1

	#BIT RC2 = PORTC.2
	//#BIT CCP1 = PORTC.2

	#BIT RC3 = PORTC.3
	//#BIT SCK = PORTC.3
	//#BIT SCL = PORTC.3

	#BIT RC4 = PORTC.4
	//#BIT SDI = PORTC.4
	//#BIT SDA = PORTC.4

	#BIT RC5 = PORTC.5
	//#BIT SDO = PORTC.5

	#BIT RC6 = PORTC.6
	//#BIT TX = PORTC.6
	//#BIT CK = PORTC.6

	#BIT RC7 = PORTC.7
	//#BIT RX = PORTC.7

#BYTE PORTD = 0x0F83
	#BIT RD0 = PORTD.0
	//#BIT PSP0 = PORTD.0

	#BIT RD1 = PORTD.1
	//#BIT PSP1 = PORTD.1

	#BIT RD2 = PORTD.2
	//#BIT PSP2 = PORTD.2

	#BIT RD3 = PORTD.3
	//#BIT PSP3 = PORTD.3

	#BIT RD4 = PORTD.4
	//#BIT PSP4 = PORTD.4

	#BIT RD5 = PORTD.5
	//#BIT PSP5 = PORTD.5
	//#BIT P1B = PORTD.5

	#BIT RD6 = PORTD.6
	//#BIT PSP6 = PORTD.6
	//#BIT P1C = PORTD.6

	#BIT RD7 = PORTD.7
	//#BIT PSP7 = PORTD.7
	//#BIT P1D = PORTD.7

#BYTE PORTE = 0x0F84
	#BIT RE0 = PORTE.0
	//#BIT RD = PORTE.0
	//#BIT NOT_RD = PORTE.0
	//#BIT AN5 = PORTE.0

	#BIT RE1 = PORTE.1
	//#BIT WR = PORTE.1
	//#BIT NOT_WR = PORTE.1
	//#BIT AN6 = PORTE.1

	#BIT RE2 = PORTE.2
	//#BIT CS = PORTE.2
	//#BIT NOT_CS = PORTE.2
	//#BIT AN7 = PORTE.2

	#BIT RE3 = PORTE.3
	//#BIT MCLR = PORTE.3
	//#BIT NOT_MCLR = PORTE.3
	//#BIT VPP = PORTE.3

#BYTE LATA = 0x0F89
	#BIT LATA0 = LATA.0
	#BIT LATA1 = LATA.1
	#BIT LATA2 = LATA.2
	#BIT LATA3 = LATA.3
	#BIT LATA4 = LATA.4
	#BIT LATA5 = LATA.5
	#BIT LATA6 = LATA.6
	#BIT LATA7 = LATA.7

#BYTE LATB = 0x0F8A
	#BIT LATB0 = LATB.0
	#BIT LATB1 = LATB.1
	#BIT LATB2 = LATB.2
	#BIT LATB3 = LATB.3
	#BIT LATB4 = LATB.4
	#BIT LATB5 = LATB.5
	#BIT LATB6 = LATB.6
	#BIT LATB7 = LATB.7

#BYTE LATC = 0x0F8B
	#BIT LATC0 = LATC.0
	#BIT LATC1 = LATC.1
	#BIT LATC2 = LATC.2
	#BIT LATC3 = LATC.3
	#BIT LATC4 = LATC.4
	#BIT LATC5 = LATC.5
	#BIT LATC6 = LATC.6
	#BIT LATC7 = LATC.7

#BYTE LATD = 0x0F8C
	#BIT LATD0 = LATD.0
	#BIT LATD1 = LATD.1
	#BIT LATD2 = LATD.2
	#BIT LATD3 = LATD.3
	#BIT LATD4 = LATD.4
	#BIT LATD5 = LATD.5
	#BIT LATD6 = LATD.6
	#BIT LATD7 = LATD.7

#BYTE LATE = 0x0F8D
	#BIT LATE0 = LATE.0
	#BIT LATE1 = LATE.1
	#BIT LATE2 = LATE.2

#BYTE TRISA = 0x0F92
	#BIT TRISA0 = TRISA.0
	#BIT TRISA1 = TRISA.1
	#BIT TRISA2 = TRISA.2
	#BIT TRISA3 = TRISA.3
	#BIT TRISA4 = TRISA.4
	#BIT TRISA5 = TRISA.5
	#BIT TRISA6 = TRISA.6
	#BIT TRISA7 = TRISA.7

#BYTE TRISB = 0x0F93
	#BIT TRISB0 = TRISB.0
	#BIT TRISB1 = TRISB.1
	#BIT TRISB2 = TRISB.2
	#BIT TRISB3 = TRISB.3
	#BIT TRISB4 = TRISB.4
	#BIT TRISB5 = TRISB.5
	#BIT TRISB6 = TRISB.6
	#BIT TRISB7 = TRISB.7

#BYTE TRISC = 0x0F94
	#BIT TRISC0 = TRISC.0
	#BIT TRISC1 = TRISC.1
	#BIT TRISC2 = TRISC.2
	#BIT TRISC3 = TRISC.3
	#BIT TRISC4 = TRISC.4
	#BIT TRISC5 = TRISC.5
	#BIT TRISC6 = TRISC.6
	#BIT TRISC7 = TRISC.7

#BYTE TRISD = 0x0F95
	#BIT TRISD0 = TRISD.0
	#BIT TRISD1 = TRISD.1
	#BIT TRISD2 = TRISD.2
	#BIT TRISD3 = TRISD.3
	#BIT TRISD4 = TRISD.4
	#BIT TRISD5 = TRISD.5
	#BIT TRISD6 = TRISD.6
	#BIT TRISD7 = TRISD.7

#BYTE TRISE = 0x0F96
	#BIT TRISE0 = TRISE.0
	#BIT TRISE1 = TRISE.1
	#BIT TRISE2 = TRISE.2

#BYTE INTCON = 0xFF2
	#BIT  RBIF	 = INTCON.0
	#BIT  INT0IF = INTCON.1
	#BIT  TMR0IF = INTCON.2
	#BIT  RBIE   = INTCON.3
	#BIT  INT0IE = INTCON.4
	#BIT  TMR0IE = INTCON.5
	#BIT  PEIE   = INTCON.6
	#BIT  GIE    = INTCON.7

#BYTE INTCON2 = 0xFF1
	#BIT  INTEDG2 = INTCON2.4
	#BIT  INTEDG1 = INTCON2.5
	#BIT  INTEDG0 = INTCON2.6
	
#BYTE T1CON = 0x0FCD
#BYTE T2CON = 0x0FCA
#BYTE T3CON = 0x0FB1

//  Acrescentar registros do PIC conforme a necessidade ...

